site_name: Llama Labs
site_description: SDK for the Llama Labs platform
site_url: https://llamalabs.ai/

theme:
    logo: assets/fixie-logo.png
    favicon: assets/fixie-logo.png
    name: 'material'
    palette:
      - scheme: 'default'
        media: '(prefers-color-scheme: light)'
        toggle:
          icon: 'material/lightbulb'
          name: "Switch to dark mode"
      - scheme: 'slate'
        media: '(prefers-color-scheme: dark)'
        primary: 'black'
        toggle:
          icon: 'material/lightbulb-outline'
          name: 'Switch to light mode'
    features:
        - navigation.sections

repo_name: llamalabs-ai/llamalabs-sdk
repo_url: https://github.com/llamalabs-ai/llamalabs-sdk
edit_uri: ""

nav:
    - Introduction: 'index.md'
    - Usage:
        - QuickStart: 'quickstart.md'
    - API Reference: 'api.md'

markdown_extensions:
  - admonition
  - codehilite:
      css_class: highlight
  - mkautodoc

extra_css:
    - css/custom.css
