site_name: Llama Labs Developer Portal
site_description: API and SDK documentation for Llama Labs
site_url: https://llamalabs.ai/

theme:
    logo: assets/llamalabs-icon.png
    favicon: assets/llamalabs-icon.png
    name: 'material'
    palette:
      - scheme: 'default'
        media: '(prefers-color-scheme: light)'
        toggle:
          icon: 'material/lightbulb'
          name: "Switch to dark mode"
      - scheme: 'slate'
        media: '(prefers-color-scheme: dark)'
        primary: 'black'
        toggle:
          icon: 'material/lightbulb-outline'
          name: 'Switch to light mode'
    features:
        - navigation.sections
        - navigation.tabs

repo_name: llamalabs-ai/llamalabs-sdk
repo_url: https://github.com/llamalabs-ai/llamalabs-sdk
edit_uri: ""

nav:
    - Introduction: 'index.md'
    - Usage:
        - QuickStart: 'quickstart.md'
    - Python SDK Reference:
        - llamalabs.client: 'api-client.md'
        - llamalabs.agents: 'api-agents.md'
    - CLI Reference: 'cli.md'
    - GraphQL Reference: 'https://app.llamalabs.ai/static/docs/index.html'


markdown_extensions:
  - admonition
  - codehilite:
      css_class: highlight
  - mkdocs-click

extra_css:
    - css/custom.css

plugins:
  - search
  - mkdocstrings